plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.shiftos.terminal'
    compileSdk 36

    defaultConfig {
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    flavorDimensions = ['brend']
    productFlavors {
        shiftos {
            dimension 'brend'
            applicationId 'com.shiftos.app'
        }
        terminalshift {
            dimension 'brend'
            applicationId 'com.shiftos.terminal'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding false

        buildConfig true
    }

    androidResources {
        ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.activity:activity-ktx:1.13.0'

    implementation 'androidx.webkit:webkit:1.17.0'
}
